# netlify.toml
# headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/*"
  to = "https://8492-168-196-203-239.ngrok-free.app/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "https://repertorionotarial.netlify.app"}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization, ngrok-skip-browser-warning"
